name: image-signed-ghat(static)
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

      - name: Log into ghcr.io
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@906ecf0fc0a80f9110f79d9e6c04b1080f4a2621
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=static

      - name: Build and push image
        id: push-step
        uses: docker/build-push-action@11be14d908760a0756f045980728ec5fb7880f74
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          file: Dockerfile.static

      - name: Attest image
        uses: actions/attest-build-provenance@v2.1.0
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push-step.outputs.digest }}
          push-to-registry: true
