name: TruffleHog OSS

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.86.1
            
          
